services:
  db:
    image: postgres:16
    container_name: newsletter_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    volumes:
      - newsletter_pg:/var/lib/postgresql/data

volumes:
  newsletter_pg:
